---
abstract: "Catmandu modules for working with MAB2 data.\r"
author:
  - 'Johann Rolschewski <rolschewski@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-MAB2
requires:
  Catmandu: 0.7
  Readonly: 1.0
  XML::LibXML::Reader: 2.0
version: 0.01
